#!/usr/bin/env python3
"""Generate the Claude-plugin layout at the repo root from the canonical skill.

The skill + slash commands live under src/pair_pressure/_data/skill/ (also
shipped in the pip package). Claude Code plugins require a fixed root layout
(skills/<name>/SKILL.md, commands/*.md), so this copies them out and stamps a
"generated" marker. Run after editing the skill; commit the generated files.
The generated copies are derived artifacts — edit the source, re-run this.
"""
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL_SRC = ROOT / "src" / "pair_pressure" / "_data" / "skill"
SKILL_DST = ROOT / "skills" / "pair-pressure"
CMD_SRC = SKILL_SRC / "templates" / "commands"
CMD_DST = ROOT / "commands"
PLUGIN_JSON = ROOT / ".claude-plugin" / "plugin.json"

MARKER = ("<!-- generated by scripts/sync_plugin.py from "
          "src/pair_pressure/_data/skill/ -- edit the source, not this copy -->")


def reset(d):
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True)


def stamp(path):
    """Insert the generated-file marker just after the YAML frontmatter (or at
    the top when there is none), so a stray edit to a copy is obviously wrong."""
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    at = 0
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                at = i + 1
                break
    lines.insert(at, MARKER + "\n")
    path.write_text("".join(lines), encoding="utf-8", newline="")


def main():
    reset(SKILL_DST)
    for name in ("SKILL.md", "CONVENTIONS.md"):
        src = SKILL_SRC / name
        if src.exists():
            dst = SKILL_DST / name
            shutil.copy2(src, dst)
            stamp(dst)

    reset(CMD_DST)
    cmds = sorted(CMD_SRC.glob("*.md"))
    for c in cmds:
        dst = CMD_DST / c.name
        shutil.copy2(c, dst)
        stamp(dst)

    assert (SKILL_DST / "SKILL.md").exists(), "SKILL.md not copied"
    assert cmds, "no command templates found"

    # Keep the plugin manifest version locked to the canonical VERSION file.
    version = (SKILL_SRC / "VERSION").read_text(encoding="utf-8").strip()
    manifest = json.loads(PLUGIN_JSON.read_text(encoding="utf-8"))
    assert manifest["version"] == version, (
        f"plugin.json version {manifest['version']!r} != VERSION {version!r} -- "
        "update .claude-plugin/plugin.json")

    print(f"synced 1 skill + {len(cmds)} commands (v{version}) -> {ROOT}")


if __name__ == "__main__":
    main()
